Numerous task and variable updates
- Use all directory variables in all templates
  - Addresses #8
  - Addresses #9
- New variables:
  - `nomad_lockfile`
  - `nomad_run_dir`
- Updated init script templates
- Updated systemd unit template
- Convert to local action plays

diff --git a/templates/nomad_debian.init.j2 b/templates/nomad_debian.init.j2
--- a/templates/nomad_debian.init.j2
+++ b/templates/nomad_debian.init.j2
@@ -8,110 +8,115 @@
 # Short-Description: distributed scheduler
 # Description:       distributed, highly available, datacenter-aware scheduler
 ### END INIT INFO
+# shellcheck disable=SC2015
+# shellcheck disable=SC1090
+# shellcheck disable=SC1091
+# shellcheck disable=SC2034
 
-PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
-DESC="nomad service discovery framework"
-NAME=nomad
-DAEMON=/usr/local/bin/$NAME
-PIDFILE=/var/run/$NAME/$NAME.pid
-DAEMON_ARGS="agent -server -config {{ nomad_config_dir }}/base.hcl -config {{ nomad_config_dir }}/{{ nomad_node_role }}.hcl ${nomad_FLAGS} >> /var/log/nomad/nomad.log 2>&1"
-USER={{ nomad_user }}
-SCRIPTNAME=/etc/init.d/$NAME
+PATH="{{ nomad_bin_dir }}:/usr/sbin:/usr/bin:/sbin:/bin"
+DESC="Nomad service discovery framework"
+NAME="nomad"
+DAEMON="{{ nomad_bin_dir }}/${NAME}"
+PIDFILE="{{ nomad_run_dir }}/${NAME}.pid"
+DAEMON_ARGS="agent -server -config {{ nomad_config_dir }}/base.hcl -config {{ nomad_config_dir }}/{{ nomad_node_role }}.hcl >> {{ nomad_log_dir }}/$NAME.log 2>&1"
+USER="{{ nomad_user }}"
+SCRIPTNAME="/etc/init.d/${NAME}"
 
-[ -x "$DAEMON" ] || exit 0
+[ -x "${DAEMON}" ] || exit 0
 
-[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+[ -r /etc/default/"${NAME}" ] && . /etc/default/"${NAME}"
 
 [ -f /etc/default/rcS ] && . /etc/default/rcS
 
 . /lib/lsb/init-functions
 
 mkrundir() {
-        [ ! -d /var/run/nomad ] && mkdir -p /var/run/nomad
-        chown $USER /var/run/nomad
+        [ ! -d "{{ nomad_run_dir }}" ] && mkdir -p "{{ nomad_run_dir }}"
+        chown "${USER}" "{{ nomad_run_dir }}"
 }
 
 do_start() {
-    mkrundir
-    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --chuid $USER --background --make-pidfile --test > /dev/null \
-        || return 1
-    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --chuid $USER --background --make-pidfile -- \
-        $DAEMON_ARGS \
-        || return 2
+  mkrundir
+  start-stop-daemon --start --quiet --pidfile "${PIDFILE}" --exec "${DAEMON}" \
+       --chuid "${USER}" --background --make-pidfile --test > /dev/null \
+      || return 1
+  start-stop-daemon --start --quiet --pidfile "${PIDFILE}" --exec "${DAEMON}" \
+      --chuid "${USER}" --background --make-pidfile -- \
+      "${DAEMON_ARGS}" \
+      || return 2
 
-    for i in `seq 1 30`; do
-        if ! start-stop-daemon --quiet --stop --test --pidfile $PIDFILE --exec $DAEMON --user $USER; then
-            RETVAL=2
-            sleep 1
-            continue
-        fi
-        if "$DAEMON" info >/dev/null; then
-            return 0
-        fi
-    done
-    return "$RETVAL"
+  for i in $(seq 1 30); do
+      if ! start-stop-daemon --quiet --stop --test --pidfile "${PIDFILE}" \
+              --exec "${DAEMON}" --user "${USER}"; then
+          RETVAL=2
+          sleep 1
+          continue
+      fi
+      if "${DAEMON}" info >/dev/null; then
+          return 0
+      fi
+  done
+  return "${RETVAL}"
 }
 
 do_stop() {
-    if ("${DAEMON}" info 2>/dev/null | grep -q 'server = false' 2>/dev/null) ; then
-        "$DAEMON" leave
-    fi
-    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
-    RETVAL="$?"
-    [ "$RETVAL" = 2 ] && return 2
-    start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
-    [ "$?" = 2 ] && return 2
-    rm -f $PIDFILE
-    return "$RETVAL"
+  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 \
+      --pidfile "${PIDFILE}" \
+      --name "${NAME}"
+  RETVAL="$?"
+  [ "${RETVAL}" = 2 ] && return 2
+  start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 \
+      --exec "${DAEMON}"
+  [ "$?" = 2 ] && return 2
+  rm -f "${PIDFILE}"
+  return "${RETVAL}"
 }
 
 do_reload() {
-    start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
-    return 0
+  start-stop-daemon --stop --signal 1 --quiet --pidfile "${PIDFILE}" \
+      --name "${NAME}"
+  return 0
 }
 
 case "$1" in
   start)
-    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+    [ "${VERBOSE}" != no ] && log_daemon_msg "Starting ${DESC}" "${NAME}"
     do_start
     case "$?" in
-        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+        0|1) [ "${VERBOSE}" != no ] && log_end_msg 0 ;;
+        2) [ "${VERBOSE}" != no ] && log_end_msg 1 ;;
     esac
     ;;
   stop)
-    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+    [ "${VERBOSE}" != no ] && log_daemon_msg "Stopping ${DESC}" "${NAME}"
     do_stop
     case "$?" in
-        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+        0|1) [ "${VERBOSE}" != no ] && log_end_msg 0 ;;
+        2) [ "${VERBOSE}" != no ] && log_end_msg 1 ;;
     esac
     ;;
-    log_daemon_msg "Restarting $DESC" "$NAME"
+  restart|force-reload)
+    log_daemon_msg "Restarting ${DESC}" "${NAME}"
     do_stop
     case "$?" in
       0|1)
         do_start
         case "$?" in
-            0) log_end_msg 0
-            ;;
-            1) log_end_msg 1
-            ;;
-            *) log_end_msg 1
-            ;;
+            0) log_end_msg 0 ;;
+            1) log_end_msg 1 ;;
+            *) log_end_msg 1 ;;
         esac
         ;;
       *)
+        # Stop failed
         log_end_msg 1
         ;;
     esac
     ;;
-  status)
-      status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
-      ;;
   *)
-    echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+    echo "Usage: ${SCRIPTNAME} {start|stop|restart|force-reload}" >&2
     exit 3
     ;;
 esac
+
 :
